minimal_mistakes_skin: "contrast"  # Change from "sunrise" to "contrast"locale: "fr-FR"
title: "Blog de Yasser "
email: "yasserkaouni@gmail.com"
description: "Explorations en mathématiques, statistiques et IA appliquées aux sciences du vivant"
url: "https://blog.yasserelkaouni.github.io"
github_username: "YasserELKAONUI"

# Redirect settings
redirect_from:
  - https://yasserelkaouni.github.io


# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-redirect-from

# Site Author
author:
  name     : "Yasser EL Kaouni"
  avatar   : "/assets/images/bio-photo.jpeg"
  bio      : " Passionné par l'IA, le deep learning et le data engineering, je suis diplômé en mathématiques appliquées, statistiques et ML pour les données du vivant."
  location : "France"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/YasserELKAOUNI"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/yasser-elkaouni/"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/YasserELKAOUNI"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/your-correct-linkedin-url/"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Categories
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


include:
  - _pages

# Big Image (fresque)
header:
  overlay_image: "/assets/images/Acropolis_Impressionist_Art.webp"
  overlay_filter: 0.5
  caption: "Bienvenue sur mon blog"
  actions:
    - label: "En savoir plus"
      url: "/about/"